/*******************************************************************************
 * @file callback.c
 * @brief USB Callbacks.
 *******************************************************************************/

//=============================================================================
// src/callback.c: generated by Hardware Configurator
//
// This file is only generated if it does not exist. Modifications in this file
// will persist even if Configurator generates code. To refresh this file,
// you must first delete it and then regenerate code.
//=============================================================================
//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8UB1_Register_Enums.h>
#include <efm8_usb.h>
#include "descriptors.h"

//-----------------------------------------------------------------------------
// Constants
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Variables
//-----------------------------------------------------------------------------
extern volatile USBD_State_TypeDef usbState;
extern volatile bool tx_done;

//-----------------------------------------------------------------------------
// Functions
//-----------------------------------------------------------------------------

void USBD_ResetCb(void) {
	usbState = USBD_STATE_NONE;
	//tx_done=true;
}

void USBD_SofCb(uint16_t sofNr) {

}
void USBD_DeviceStateChangeCb(USBD_State_TypeDef oldState,
		USBD_State_TypeDef newState) {
	usbState = newState;
	//tx_done=true;
}
uint16_t USBD_XferCompleteCb(uint8_t epAddr, USB_Status_TypeDef status,
		uint16_t xferred, uint16_t remaining) {
	tx_done=true;
	return 0;
}
bool USBD_IsSelfPoweredCb(void){
	return true;
}
USB_Status_TypeDef USBD_SetupCmdCb(SI_VARIABLE_SEGMENT_POINTER(setup,
                                                               USB_Setup_TypeDef,
                                                               MEM_MODEL_SEG)){
	//tx_done=true;
	return USB_STATUS_REQ_UNHANDLED;
}
void USBD_EnterHandler(void){
	//tx_done=true;

}
void USBD_ExitHandler(void){
	//tx_done=true;
}

