.PHONY: clean All

All:
	@echo "----------Building project:[ usbmon - Debug ]----------"
	@cd "usbmon" && $(MAKE) -f  "usbmon.mk"
clean:
	@echo "----------Cleaning project:[ usbmon - Debug ]----------"
	@cd "usbmon" && $(MAKE) -f  "usbmon.mk" clean
